services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - user=userApp
    ports:
      - "5001:5001"
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    # profiles:
    #  - app-only

  database:
    container_name: postgres-dev
    image: postgres:16.0-alpine3.18
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    # profiles:
    #  - db-only
