version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - user=userApp
        ports:
            - "5001:5001"
            - "3000:3000"
        volumes:
            - .:/usr/src/app

